language: node_js
node_js:
  - "6"
  - "7"
install: true
script:
  - npm install --ignore-scripts
  - npm run lint
  - npm run test:js
  - npm run build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.npm
after_success: npm run test:cov
